# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.runs/synth_1/.Xil/Vivado-18076-DESKTOP-QSFIJ7U/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tftg256-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/adder16_6.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/alu_1.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/and2_16.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/autotester_2.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/basic_add16_17.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/basic_add6_14.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/boolean16_8.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/compare16_11.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/counter_12.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/divider16_10.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/equal16_13.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/full_adder_15.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/multiplier16_7.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/mux2_5.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/mux4_4.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/reset_conditioner_3.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/shifter16_9.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/two_compliment16_18.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/xor2_19.v
      C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/au_top_0.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.runs/synth_1/.Xil/Vivado-18076-DESKTOP-QSFIJ7U/realtime/au_top_0_synth.xdc
    rt::sdcChecksum
    set rt::top au_top_0
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.runs/synth_1/.Xil/Vivado-18076-DESKTOP-QSFIJ7U/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
