# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/adder16_6.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/alu_1.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/and2_16.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/autotester_2.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/basic_add16_17.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/basic_add6_14.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/boolean16_8.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/compare16_11.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/counter_12.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/divider16_10.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/equal16_13.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/full_adder_15.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/multiplier16_7.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/mux2_5.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/mux4_4.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/reset_conditioner_3.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/shifter16_9.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/two_compliment16_18.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/xor2_19.v
  C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/vivado/ALU_FPGA/ALU_FPGA.srcs/sources_1/imports/verilog/au_top_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/constraint/custom.xdc
set_property used_in_implementation false [get_files C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/work/constraint/custom.xdc]

read_xdc C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/constraint/custom.xdc
set_property used_in_implementation false [get_files C:/Users/USER/Documents/GitHub/naffins/50.002_alu_fpga/ALU_FPGA/constraint/custom.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top au_top_0 -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef au_top_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file au_top_0_utilization_synth.rpt -pb au_top_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
