/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module and2_16 (
    input a,
    input b,
    output reg s
  );
  
  
  
  always @* begin
    s = a & b;
  end
endmodule
