/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare16_11 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] cmp
  );
  
  
  
  reg less_than_result;
  
  wire [1-1:0] M_selector_mux_out;
  reg [1-1:0] M_selector_mux_inp0;
  reg [1-1:0] M_selector_mux_inp1;
  reg [1-1:0] M_selector_mux_inp2;
  reg [1-1:0] M_selector_mux_inp3;
  reg [1-1:0] M_selector_mux_s0;
  reg [1-1:0] M_selector_mux_s1;
  mux4_4 selector_mux (
    .inp0(M_selector_mux_inp0),
    .inp1(M_selector_mux_inp1),
    .inp2(M_selector_mux_inp2),
    .inp3(M_selector_mux_inp3),
    .s0(M_selector_mux_s0),
    .s1(M_selector_mux_s1),
    .out(M_selector_mux_out)
  );
  
  always @* begin
    cmp[1+14-:15] = 15'h0000;
    cmp[0+0-:1] = M_selector_mux_out;
    M_selector_mux_s1 = alufn[2+0-:1];
    M_selector_mux_s0 = alufn[1+0-:1];
    M_selector_mux_inp0 = 1'h0;
    M_selector_mux_inp1 = z;
    less_than_result = v ^ n;
    M_selector_mux_inp2 = less_than_result;
    M_selector_mux_inp3 = less_than_result | z;
  end
endmodule
