/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module equal16_13 (
    input [15:0] a,
    input [15:0] b,
    output reg result
  );
  
  
  
  wire [(5'h10+0)-1:0] M_xorgates_out;
  reg [(5'h10+0)-1:0] M_xorgates_a;
  reg [(5'h10+0)-1:0] M_xorgates_b;
  
  genvar GEN_xorgates0;
  generate
  for (GEN_xorgates0=0;GEN_xorgates0<5'h10;GEN_xorgates0=GEN_xorgates0+1) begin: xorgates_gen_0
    xor2_19 xorgates (
      .a(M_xorgates_a[GEN_xorgates0*(1)+(1)-1-:(1)]),
      .b(M_xorgates_b[GEN_xorgates0*(1)+(1)-1-:(1)]),
      .out(M_xorgates_out[GEN_xorgates0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    M_xorgates_a = a;
    M_xorgates_b = b;
    result = ~(M_xorgates_out[0+0-:1] | M_xorgates_out[1+0-:1] | M_xorgates_out[2+0-:1] | M_xorgates_out[3+0-:1] | M_xorgates_out[4+0-:1] | M_xorgates_out[5+0-:1] | M_xorgates_out[6+0-:1] | M_xorgates_out[7+0-:1] | M_xorgates_out[8+0-:1] | M_xorgates_out[9+0-:1] | M_xorgates_out[10+0-:1] | M_xorgates_out[11+0-:1] | M_xorgates_out[12+0-:1] | M_xorgates_out[13+0-:1] | M_xorgates_out[14+0-:1] | M_xorgates_out[15+0-:1]);
  end
endmodule
